import type { Metadata } from "next";
import "../styles/globals.scss";
import "./globals.css";
import MainLayout from "../layouts/MainLayout/MainLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <MainLayout>
          <div id="nymbleup-root">{children}</div>
        </MainLayout>
        <div id="nymbleup-portal"></div>
      </body>
    </html>
  );
}
